name: Code Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-python-dependencies

      - name: Run Unit Tests
        run: just detector::unit-test

      - name: Override Coverage Source Path for SonarCloud
        run: sed -i "s/<source>\/home\/runner\/work\/tech-detective\/tech-detective\/detector<\/source>/<source>\/github\/workspace\/detector<\/source>/g" /home/runner/work/tech-detective/tech-detective/detector/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  end-to-end-test:
    name: Run End to End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-test-dependencies
        with:
          install-playwright-dependencies: "true"

      - name: Run End to End Tests
        run: just tests::end-to-end-tests
