name: "Code Quality"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  check-code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Lint and Format everything but Python/JavaScript/TypeScript
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LINTER_RULES_PATH: .github/super-linter-configurations
          YAML_ERROR_ON_WARNING: true
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_CSS: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          VALIDATE_JSX_PRETTIER: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          VALIDATE_TSX_PRETTIER: false

  check-python-code-format-and-quality:
    name: Check Python Code Format and Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-python-dependencies

      - name: Check Python Code Quality (Ruff)
        run: just detector::ruff-lint

      - name: Check Python Code Format (Ruff)
        run: just detector::ruff-format

      - name: Check Python Code for Dead Code (Vulture)
        run: just detector::vulture

  check-typescript-code-format-and-quality:
    name: Check TypeScript Code Format and Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "dashboard/package.json"
          cache: "npm"
          cache-dependency-path: "dashboard/package-lock.json"

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install Node Dependencies
        run: just dashboard::ci-install

      - name: Run Prettier
        run: just dashboard::prettier-check

      - name: Run ESLint
        run: just dashboard::eslint-check

  check-markdown-links:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Markdown links
        uses: UmbrellaDocs/action-linkspector@v1.2.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          config_file: .github/other-configurations/.linkspector.yml
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter

  check-justfile-format:
    name: Check Justfile Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Check Justfile Format
        run: just format-check
