name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-detector:
    name: Run Detector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-dependencies

      - name: Run Detector
        run: just detector::run
        env:
          FORCE_COLOR: "true" # Force log colour output
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Upload Detector Output File
        uses: actions/upload-artifact@v4.4.3
        with:
          name: project-technologies-and-frameworks
          path: project_technologies_and_frameworks.json

  build-site:
    name: Build Site
    needs: run-detector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Download Detector Output File
        uses: actions/download-artifact@v4.1.8
        with:
          name: project-technologies-and-frameworks

      - name: Install, build, and upload site
        uses: withastro/action@v3.0.0
        with:
          path: dashboard
          node-version: 22

  deploy-site:
    name: Deploy Site
    needs: build-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

  schema-validation:
    name: Validate Schema
    needs: run-detector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Detector Dependencies
        uses: ./.github/actions/setup-test-dependencies

      - name: Download Detector Output File
        uses: actions/download-artifact@v4.1.8
        with:
          name: project-technologies-and-frameworks
          path: tests/schema_validation

      - name: Schema Validation Test
        run: just tests::validate-schema

  end-to-end-test:
    name: Run End to End Tests
    needs: deploy-site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-test-dependencies
        with:
          install-playwright-dependencies: "true"

      - name: Run End to End Tests
        run: just tests::end-to-end-tests
