name: "Pull Request Checks"

on:
  pull_request:
    types:
      [
        opened,
        edited,
        unlocked,
        labeled,
        synchronize,
        reopened,
        ready_for_review,
      ]

permissions:
  pull-requests: write

jobs:
  check-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          allowed_prefixes: "feat: ,fix: ,bug: ,ci: ,refactor: ,docs: ,build: ,chore(,deps(,chore: ,feat!: ,fix!: ,refactor!: ,test: " # title should start with the given prefix
